---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: discourse
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DISCOURSE_DB_USERNAME: postgres 
  DISCOURSE_DB_PASSWORD: postgres 
  DISCOURSE_DB_HOST: postgres
  DISCOURSE_DB_PORT: "5432"
  DISCOURSE_REDIS_HOST: "redis-master" 
  DISCOURSE_REDIS_SLAVE_HOST: "redis-slave"
  LANG: "en_US.UTF-8"
  RAILS_ENV: "production"
  UNICORN_WORKERS: "2"
  UNICORN_SIDEKIQS: "1"
  RUBY_GLOBAL_METHOD_CACHE_SIZE: "131072"
  RUBY_GC_HEAP_GROWTH_MAX_SLOTS: "40000"
  RUBY_GC_HEAP_INIT_SLOTS: "400000"
  RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: "1.5"
  DISCOURSE_HOSTNAME: localhost 
  DISCOURSE_DEVELOPER_EMAILS: "xc0d3@outlook.com"
  DISCOURSE_SMTP_ADDRESS: "in-v3.mailjet.com"
  DISCOURSE_SMTP_PORT: "587"
  DISCOURSE_SMTP_USER_NAME: "b1db43122639c2ea6a2dea62db691240"
  DISCOURSE_SMTP_PASSWORD: "950462fc3dd60f225edf60fa0ef26380"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer 
  ports:
   - port: 5432
  selector:
   app: postgres

