---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: xcode1024/frontend:v3 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: postgres-config

---

# The polls service provides a load-balancing proxy over the polls app
# pods. By specifying the type as a 'LoadBalancer', Container Engine will
# create an external HTTP load balancer.
# For more information about Services see:
#   https://cloud.google.com/container-engine/docs/services/
# For more information about external HTTP load balancing see:
#   https://cloud.google.com/container-engine/docs/load-balancer
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: frontend
